import ThemeRegistry from "./MuiSetup";
import Script from "next/script";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:wght@100..900&display=swap"
          rel="stylesheet"
        >
        </link>
      </head>
      <body>
        <ThemeRegistry options={{ key: "mui" }}>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
